FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY Models/*.csproj ./Models/
COPY Feedback/*.csproj ./Feedback/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env ./app/Feedback/out .
COPY --from=build-env ./app/Models/out .
ENTRYPOINT ["dotnet", "Feedback.dll"]