FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY Models/*.csproj ./Models/
COPY Repository/*.csproj ./Repository/
COPY GetRatesMongo/*.csproj ./GetRatesMongo/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env ./app/GetRatesMongo/out .
COPY --from=build-env ./app/Models/out .
COPY --from=build-env ./app/Repository/out .
ENTRYPOINT ["dotnet", "GetRatesMongo.dll"]